sudo: required
services:
  - docker

before_install:
  - docker build -t bentlema/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bentlema/react-test npm test -- --coverage

after_success:
  - docker build -t bentlema/multi-client ./client
  - docker build -t bentlema/multi-nginx ./nginx
  - docker build -t bentlema/multi-server ./server
  - docker build -t bentlema/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bentlema/multi-client
  - docker push bentlema/multi-nginx
  - docker push bentlema/multi-server
  - docker push bentlema/multi-worker

deploy:
  provider: "elasticbeanstalk"
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-305170822333"
  bucket_path: "multi-docker"
  on:
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
